feat: add pattern option
qiwi/semantic-release-gh-pages-plugin pull request #278
Opened 2024-12-04 23:43 UTC by dvirtz

Closes #110

## Changes

add pattern option which is passed as gh-pages [src](https://github.com/tschaub/gh-pages?tab=readme-ov-file#optionssrc) option

- [x] New code is covered by tests
- [x] All the changes are mentioned in docs (readme.md)

2024-12-05 19:32 UTC, antongolub requested changes

2024-12-05 19:32 UTC, antongolub commented on README.md
> +yarn add @wiki/semantic-release-gh-pages-plugin --dev
I'm afraid, we're not ready to change the pkg name and scope )

2024-12-05 21:48 UTC, dvirtz reviewed
rebased to fix commit author

2024-12-07 19:43 UTC, antongolub commented
@dvirtz,

Another rebase is required to fix the test

2024-12-07 20:59 UTC, dvirtz reviewed
> @dvirtz,
> 
> Yet another rebase is required to fix the test
> 
>  

done

2024-12-08 14:56 UTC, antongolub approved these changes
lgtm

2024-12-08 15:10 UTC, merged